# Generated by Django 5.1.3 on 2024-12-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table='auth_user_2',
        ),
    ]
